#!/bin/bash
set -e

echo "============================================================"
echo "Setup Custom Domain: api.hypelive.app"
echo "============================================================"
echo ""
echo "The wrangler.toml already has the route configured:"
echo "  routes = ["
echo "    { pattern = \"api.hypelive.app/webhooks/post-for-me\", custom_domain = true }"
echo "  ]"
echo ""
echo "But custom domains require API Token authentication (not OAuth)."
echo ""
echo "Option 1: Manual Setup (Recommended)"
echo "====================================="
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select zone: hypelive.app"
echo "3. Go to: Workers & Pages > Custom Domains"
echo "4. Click: Add Custom Domain"
echo "5. Enter:"
echo "   - Domain: api.hypelive.app"
echo "   - Service: hypesocial-webhook"
echo "   - Environment: production"
echo "6. Click: Add Domain"
echo ""
echo "Option 2: Create API Token for Automation"
echo "==========================================="
echo "1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "2. Click: Create Token"
echo "3. Use template: 'Edit Cloudflare Workers'"
echo "4. OR Create Custom Token with:"
echo "   - Zone:Read (for hypelive.app)"
echo "   - Workers Scripts:Edit"
echo "   - Account:Read"
echo "5. Copy the token and run:"
echo "   export CLOUDFLARE_API_TOKEN=your_token"
echo "   npx tsx scripts/cloudflare-mcp-setup.ts"
echo ""
echo "Option 3: Use Cloudflare Tunnel (for local testing)"
echo "===================================================="
echo "Your existing tunnel: acae9bbc-5460-4c47-8750-1d5b4071b021"
echo "Can expose localhost:3000 to a subdomain"
echo ""
echo "Run: cloudflared tunnel run acae9bbc-5460-4c47-8750-1d5b4071b021"
echo ""
echo "============================================================"
echo "Current Worker URL:"
echo "  https://hypesocial-webhook.hypelive.workers.dev"
echo ""
echo "Target Custom Domain:"
echo "  https://api.hypelive.app/webhooks/post-for-me"
echo "============================================================"
