"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useBuilderStore } from "./store";
import { blockRegistry } from "./blocks/registry";
import { hexToHsl } from "./lib/theme";
import type { BuilderBlock } from "./blocks/types";
import { useState, useMemo } from "react";
import { Copy, Check } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";

function generatePageCode(blocks: BuilderBlock[], theme: { primaryColor: string; borderRadius: number; fontFamily: string }) {
  const usedComponents = new Set<string>();
  const blockCodes: string[] = [];

  blocks.forEach((block: BuilderBlock) => {
    const entry = blockRegistry[block.type];
    const code = entry.codeTemplate(block.props);
    blockCodes.push(code);

    // Naive component detection from code templates
    const componentMatches = code.match(/<(Badge|Button|Card|CardContent|CardDescription|CardFooter|CardHeader|CardTitle|Avatar|AvatarFallback|AvatarImage|Input|Separator|Accordion|AccordionContent|AccordionItem|AccordionTrigger|Star|Check|ArrowRight|Play|Twitter|Github|Zap|Shield|Sparkles|BarChart3|Label|Layout|Wand2|MousePointer2|Image as ImageIcon)[\s>]/g);
    if (componentMatches) {
      componentMatches.forEach((m: string) => {
        const name = m.slice(1).replace(/[\s>]/g, "");
        if (name) usedComponents.add(name);
      });
    }
  });

  // Normalize imports to shadcn/ui components that actually exist in this project
  const shadcnImports = Array.from(usedComponents).filter((c) =>
    [
      "Badge",
      "Button",
      "Card",
      "CardContent",
      "CardDescription",
      "CardFooter",
      "CardHeader",
      "CardTitle",
      "Avatar",
      "AvatarFallback",
      "AvatarImage",
      "Input",
      "Separator",
      "Accordion",
      "AccordionContent",
      "AccordionItem",
      "AccordionTrigger",
      "Label",
    ].includes(c)
  );

  const iconImports = Array.from(usedComponents).filter((c) =>
  ["ArrowRight", "Play", "Star", "Check", "Twitter", "Github", "Zap", "Shield", "Sparkles", "BarChart3", "Wand2", "MousePointer2", "Layout", "Image"].includes(c)
  );

  const imports: string[] = [];
  if (shadcnImports.length) {
    imports.push(`import { ${shadcnImports.join(", ")} } from "@/components/ui";`);
  }
  if (iconImports.length) {
    imports.push(`import { ${iconImports.join(", ")} } from "lucide-react";`);
  }

  const { h, s, l } = hexToHsl(theme.primaryColor);
  const styleProp = `style={{ ["--primary"]: "${h} ${s}% ${l}%", ["--radius"]: "${theme.borderRadius / 16}rem", fontFamily: "${theme.fontFamily}" }}`;
  const body = blockCodes.join("\n\n");

  return `import type { Metadata } from "next";
${imports.join("\n")}

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by HypeSocial Builder",
};

export default function Page() {
  return (
    <main className="min-h-screen bg-background" ${styleProp}>
${body
  .split("\n")
  .map((line) => "      " + line)
  .join("\n")}
    </main>
  );
}
`;
}

export function ExportDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (val: boolean) => void;
}) {
  const { blocks, theme } = useBuilderStore();
  const [copied, setCopied] = useState(false);

  const code = useMemo(() => generatePageCode(blocks, theme), [blocks, theme]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>Export Code</DialogTitle>
          <DialogDescription>
            Copy the generated Next.js page code below.
          </DialogDescription>
        </DialogHeader>
        <div className="mt-2 space-y-3">
          <div className="flex justify-end">
            <Button size="sm" onClick={handleCopy} className="gap-1.5">
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
          <ScrollArea className="max-h-[60vh]">
            <pre className="rounded-lg bg-muted p-4 text-xs leading-relaxed text-foreground">
              <code>{code}</code>
            </pre>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
