import type { SocialTemplate, BuilderTemplateV2 } from "./types";

export const socialTemplates: SocialTemplate[] = [
  {
    id: "product-promo-square",
    name: "Product Promo",
    format: "ig-post",
    layers: [
      {
        id: "bg",
        type: "background",
        name: "Background",
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 0,
        props: { color: "#f8fafc" },
      },
      {
        id: "product-img",
        type: "image",
        name: "Product Image",
        x: 25,
        y: 15,
        width: 50,
        height: 45,
        rotation: 0,
        zIndex: 1,
        props: {
          src: "",
          objectFit: "contain",
          rounded: true,
        },
      },
      {
        id: "headline",
        type: "text",
        name: "Headline",
        x: 10,
        y: 65,
        width: 80,
        height: 12,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "New Collection",
          fontSize: 28,
          fontWeight: 700,
          color: "#0f172a",
          align: "center",
        },
      },
      {
        id: "price",
        type: "text",
        name: "Price",
        x: 10,
        y: 78,
        width: 80,
        height: 10,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "$49.00",
          fontSize: 22,
          fontWeight: 600,
          color: "#2563eb",
          align: "center",
        },
      },
      {
        id: "cta",
        type: "button",
        name: "Shop Now",
        x: 30,
        y: 88,
        width: 40,
        height: 8,
        rotation: 0,
        zIndex: 3,
        props: {
          text: "Shop Now",
          variant: "default",
          rounded: true,
        },
      },
    ],
  },
  {
    id: "quote-minimal",
    name: "Quote Card",
    format: "ig-post",
    layers: [
      {
        id: "bg",
        type: "background",
        name: "Background",
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 0,
        props: { color: "#0f172a" },
      },
      {
        id: "quote",
        type: "text",
        name: "Quote",
        x: 10,
        y: 25,
        width: 80,
        height: 40,
        rotation: 0,
        zIndex: 1,
        props: {
          text: "Design is not just what it looks like and feels like. Design is how it works.",
          fontSize: 20,
          fontWeight: 500,
          color: "#ffffff",
          align: "center",
        },
      },
      {
        id: "author",
        type: "text",
        name: "Author",
        x: 10,
        y: 70,
        width: 80,
        height: 8,
        rotation: 0,
        zIndex: 1,
        props: {
          text: "— Steve Jobs",
          fontSize: 14,
          fontWeight: 400,
          color: "#94a3b8",
          align: "center",
        },
      },
    ],
  },
  {
    id: "story-sale",
    name: "Story Sale",
    format: "ig-story",
    layers: [
      {
        id: "bg",
        type: "background",
        name: "Background",
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 0,
        props: { color: "#7c3aed" },
      },
      {
        id: "badge",
        type: "shape",
        name: "Sale Badge",
        x: 35,
        y: 12,
        width: 30,
        height: 8,
        rotation: 0,
        zIndex: 1,
        props: {
          shape: "pill",
          color: "#facc15",
          text: "FLASH SALE",
          textColor: "#0f172a",
        },
      },
      {
        id: "discount",
        type: "text",
        name: "Discount",
        x: 10,
        y: 30,
        width: 80,
        height: 20,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "50% OFF",
          fontSize: 48,
          fontWeight: 800,
          color: "#ffffff",
          align: "center",
        },
      },
      {
        id: "sub",
        type: "text",
        name: "Subline",
        x: 10,
        y: 55,
        width: 80,
        height: 8,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "Limited time only",
          fontSize: 16,
          fontWeight: 400,
          color: "#e2e8f0",
          align: "center",
        },
      },
      {
        id: "cta",
        type: "button",
        name: "Swipe Up",
        x: 20,
        y: 85,
        width: 60,
        height: 8,
        rotation: 0,
        zIndex: 3,
        props: {
          text: "Swipe Up →",
          variant: "secondary",
          rounded: true,
        },
      },
    ],
  },
  {
    id: "announcement-clean",
    name: "Announcement",
    format: "ig-carousel",
    layers: [
      {
        id: "bg",
        type: "background",
        name: "Background",
        x: 0,
        y: 0,
        width: 100,
        height: 100,
        rotation: 0,
        zIndex: 0,
        props: { color: "#ffffff" },
      },
      {
        id: "hero-img",
        type: "image",
        name: "Hero Image",
        x: 0,
        y: 0,
        width: 100,
        height: 55,
        rotation: 0,
        zIndex: 1,
        props: { src: "", objectFit: "cover", rounded: false },
      },
      {
        id: "title",
        type: "text",
        name: "Title",
        x: 8,
        y: 62,
        width: 84,
        height: 12,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "We are launching soon",
          fontSize: 24,
          fontWeight: 700,
          color: "#0f172a",
          align: "left",
        },
      },
      {
        id: "body",
        type: "text",
        name: "Body",
        x: 8,
        y: 75,
        width: 84,
        height: 12,
        rotation: 0,
        zIndex: 2,
        props: {
          text: "Stay tuned for updates and early access.",
          fontSize: 14,
          fontWeight: 400,
          color: "#475569",
          align: "left",
        },
      },
    ],
  },
];

export function getTemplateById(id: string) {
  return socialTemplates.find((t) => t.id === id);
}

export function toBuilderTemplateV2(template: SocialTemplate): BuilderTemplateV2 {
  return {
    id: template.id,
    name: template.name,
    format: template.format,
    pages: [
      {
        id: `${template.id}-page-1`,
        name: "Page 1",
        layers: JSON.parse(JSON.stringify(template.layers)),
        canvasBackground: { color: template.theme?.backgroundColor || "#ffffff", image: "" },
      },
    ],
    theme: {
      primaryColor: template.theme?.primaryColor || "#2563eb",
      borderRadius: 8,
      fontFamily: "Inter",
      backgroundColor: template.theme?.backgroundColor || "#ffffff",
    },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
